name: "CI"

on:
  push:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Check format
        run: |
          cargo fmt --all -- --check

      - name: Clippy
        run: |
          cargo lint

      - name: Build
        run: cargo build --verbose

      - name: Run tests (rust-crypto)
        run: cargo test --verbose --no-default-features --features rust-crypto

      - name: Run tests (ring)
        run: cargo test --verbose 
